# Site Settings
title: Khanh Resume
description: "Curriculum Vitae of khanh@agiletech.vn"
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Khanh Pham Gia
tagline: Full Stack Developer
pic: avatar.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A Full-Stack Developer with highly passionate in studying and applying 
new technologies in product development, as well as enterprise area. Large background 
in multiple platforms as web-app, mobile-app and server-app. Can work independently or 
in a team (prefer working in a team which allows continuous sharing and communicating). 
Solution Architect is always my goal. Use English confidently.'

#sidebar links
email: khanh@agiletech.vn
phone: '+84 1662 95 2222'
website: agiletech.vn #do not add http://
linkedin: pham-khanh
github: vjtc0n
twitter: 'vjtc0n'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
